package TypeChart;

import java.util.Objects;

public enum Database {
    Normal1("Normal", "Normal", "Normal"),
    Normal2("Normal", "Fire", "Normal"),
    Normal3("Normal", "Water", "Normal"),
    Normal4("Normal", "Electric", "Normal"),
    Normal5("Normal", "Grass", "Normal"),
    Normal6("Normal", "Ice", "Normal"),
    Normal7("Normal", "Fighting", "Normal"),
    Normal8("Normal", "Poison", "Normal"),
    Normal9("Normal", "Ground", "Normal"),
    Normal10("Normal", "Flying", "Normal"),
    Normal11("Normal", "Psychic", "Normal"),
    Normal12("Normal", "Bug", "Normal"),
    Normal13("Normal", "Rock", "Not very effective"),
    Normal14("Normal", "Ghost", "No effect"),
    Normal15("Normal", "Dragon", "Normal"),
    Normal16("Normal", "Dark", "Normal"),
    Normal17("Normal", "Steel", "Not very effective"),
    Normal18("Normal", "Fairy", "Normal"),

    Fire1("Fire", "Normal", "Normal"),
    Fire2("Fire", "Fire", "Not very effective"),
    Fire3("Fire", "Water", "Not very effective"),
    Fire4("Fire", "Electric", "Normal"),
    Fire5("Fire", "Grass", "Super-effective"),
    Fire6("Fire", "Ice", "Super-effective"),
    Fire7("Fire", "Fighting", "Normal"),
    Fire8("Fire", "Poison", "Normal"),
    Fire9("Fire", "Ground", "Normal"),
    Fire10("Fire", "Flying", "Normal"),
    Fire11("Fire", "Psychic", "Normal"),
    Fire12("Fire", "Bug", "Super-effective"),
    Fire13("Fire", "Rock", "Not very effective"),
    Fire14("Fire", "Ghost", "Normal"),
    Fire15("Fire", "Dragon", "Not very effective"),
    Fire16("Fire", "Dark", "Normal"),
    Fire17("Fire", "Steel", "Super-effective"),
    Fire18("Fire", "Fairy", "Normal"),

    Water1("Water", "Normal", "Normal"),
    Water2("Water", "Fire", "Super-effective"),
    Water3("Water", "Water", "Not very effective"),
    Water4("Water", "Electric", "Normal"),
    Water5("Water", "Grass", "Not very effective"),
    Water6("Water", "Ice", "Normal"),
    Water7("Water", "Fighting", "Normal"),
    Water8("Water", "Poison", "Normal"),
    Water9("Water", "Ground", "Super-effective"),
    Water10("Water", "Flying", "Normal"),
    Water11("Water", "Psychic", "Normal"),
    Water12("Water", "Bug", "Normal"),
    Water13("Water", "Rock", "Super-effective"),
    Water14("Water", "Ghost", "Normal"),
    Water15("Water", "Dragon", "Not very effective"),
    Water16("Water", "Dark", "Normal"),
    Water17("Water", "Steel", "Normal"),
    Water18("Water", "Fairy", "Normal"),

    ELECTRIC1("Electric", "Normal", "Normal"),
    ELECTRIC2("Electric", "Fire", "Normal"),
    ELECTRIC3("Electric", "Water", "Super-effective"),
    ELECTRIC4("Electric", "Electric", "Not very effective"),
    ELECTRIC5("Electric", "Grass", "Not very effective"),
    ELECTRIC6("Electric", "Ice", "Normal"),
    ELECTRIC7("Electric", "Fighting", "Normal"),
    ELECTRIC8("Electric", "Poison", "Normal"),
    ELECTRIC9("Electric", "Ground", "No effect"),
    ELECTRIC10("Electric", "Flying", "Super-effective"),
    ELECTRIC11("Electric", "Psychic", "Normal"),
    ELECTRIC12("Electric", "Bug", "Normal"),
    ELECTRIC13("Electric", "Rock", "Normal"),
    ELECTRIC14("Electric", "Ghost", "Normal"),
    ELECTRIC15("Electric", "Dragon", "Not very effective"),
    ELECTRIC16("Electric", "Dark", "Normal"),
    ELECTRIC17("Electric", "Steel", "Normal"),
    ELECTRIC18("Electric", "Fairy", "Normal"),

    GRASS1("Grass", "Normal", "Normal"),
    GRASS2("Grass", "Fire", "Not very effective"),
    GRASS3("Grass", "Water", "Super-effective"),
    GRASS4("Grass", "Electric", "Normal"),
    GRASS5("Grass", "Grass", "Not very effective"),
    GRASS6("Grass", "Ice", "Normal"),
    GRASS7("Grass", "Fighting", "Normal"),
    GRASS8("Grass", "Poison", "Not very effective"),
    GRASS9("Grass", "Ground", "Super-effective"),
    GRASS10("Grass", "Flying", "Not very effective"),
    GRASS11("Grass", "Psychic", "Normal"),
    GRASS12("Grass", "Bug", "Not very effective"),
    GRASS13("Grass", "Rock", "Super-effective"),
    GRASS14("Grass", "Ghost", "Normal"),
    GRASS15("Grass", "Dragon", "Not very effective"),
    GRASS16("Grass", "Dark", "Normal"),
    GRASS17("Grass", "Steel", "Not very effective"),
    GRASS18("Grass", "Fairy", "Normal"),

    ICE1("Ice", "Normal", "Normal"),
    ICE2("Ice", "Fire", "Not very effective"),
    ICE3("Ice", "Water", "Not very effective"),
    ICE4("Ice", "Electric", "Normal"),
    ICE5("Ice", "Grass", "Super-effective"),
    ICE6("Ice", "Ice", "Not very effective"),
    ICE7("Ice", "Fighting", "Normal"),
    ICE8("Ice", "Poison", "Normal"),
    ICE9("Ice", "Ground", "Super-effective"),
    ICE10("Ice", "Flying", "Super-effective"),
    ICE11("Ice", "Psychic", "Normal"),
    ICE12("Ice", "Bug", "Normal"),
    ICE13("Ice", "Rock", "Normal"),
    ICE14("Ice", "Ghost", "Normal"),
    ICE15("Ice", "Dragon", "Super-effective"),
    ICE16("Ice", "Dark", "Normal"),
    ICE17("Ice", "Steel", "Not very effective"),
    ICE18("Ice", "Fairy", "Normal"),

    FIGHTING1("Fighting", "Normal", "Super-effective"),
    FIGHTING2("Fighting", "Fire", "Normal"),
    FIGHTING3("Fighting", "Water", "Normal"),
    FIGHTING4("Fighting", "Electric", "Normal"),
    FIGHTING5("Fighting", "Grass", "Normal"),
    FIGHTING6("Fighting", "Ice", "Super-effective"),
    FIGHTING7("Fighting", "Fighting", "Normal"),
    FIGHTING8("Fighting", "Poison", "Not very effective"),
    FIGHTING9("Fighting", "Ground", "Normal"),
    FIGHTING10("Fighting", "Flying", "Not very effective"),
    FIGHTING11("Fighting", "Psychic", "Not very effective"),
    FIGHTING12("Fighting", "Bug", "Not very effective"),
    FIGHTING13("Fighting", "Rock", "Super-effective"),
    FIGHTING14("Fighting", "Ghost", "No effect"),
    FIGHTING15("Fighting", "Dragon", "Normal"),
    FIGHTING16("Fighting", "Dark", "Super-effective"),
    FIGHTING17("Fighting", "Steel", "Super-effective"),
    FIGHTING18("Fighting", "Fairy", "Not very effective"),

    POISON1("Poison", "Normal", "Normal"),
    POISON2("Poison", "Fire", "Normal"),
    POISON3("Poison", "Water", "Normal"),
    POISON4("Poison", "Electric", "Normal"),
    POISON5("Poison", "Grass", "Super-effective"),
    POISON6("Poison", "Ice", "Normal"),
    POISON7("Poison", "Fighting", "Normal"),
    POISON8("Poison", "Poison", "Not very effective"),
    POISON9("Poison", "Ground", "Not very effective"),
    POISON10("Poison", "Flying", "Normal"),
    POISON11("Poison", "Psychic", "Normal"),
    POISON12("Poison", "Bug", "Normal"),
    POISON13("Poison", "Rock", "Not very effective"),
    POISON14("Poison", "Ghost", "Not very effective"),
    POISON15("Poison", "Dragon", "Normal"),
    POISON16("Poison", "Dark", "Normal"),
    POISON17("Poison", "Steel", "No effect"),
    POISON18("Poison", "Fairy", "Super-effective"),

    GROUND1("Ground", "Normal", "Normal"),
    GROUND2("Ground", "Fire", "Super-effective"),
    GROUND3("Ground", "Water", "Normal"),
    GROUND4("Ground", "Electric", "Super-effective"),
    GROUND5("Ground", "Grass", "Not very effective"),
    GROUND6("Ground", "Ice", "Normal"),
    GROUND7("Ground", "Fighting", "Normal"),
    GROUND8("Ground", "Poison", "Super-effective"),
    GROUND9("Ground", "Ground", "Normal"),
    GROUND10("Ground", "Flying", "No effect"),
    GROUND11("Ground", "Psychic", "Normal"),
    GROUND12("Ground", "Bug", "Not very effective"),
    GROUND13("Ground", "Rock", "Super-effective"),
    GROUND14("Ground", "Ghost", "Normal"),
    GROUND15("Ground", "Dragon", "Normal"),
    GROUND16("Ground", "Dark", "Normal"),
    GROUND17("Ground", "Steel", "Super-effective"),
    GROUND18("Ground", "Fairy", "Normal"),

    FLYING1("Flying", "Normal", "Normal"),
    FLYING2("Flying", "Fire", "Normal"),
    FLYING3("Flying", "Water", "Normal"),
    FLYING4("Flying", "Electric", "Not very effective"),
    FLYING5("Flying", "Grass", "Super-effective"),
    FLYING6("Flying", "Ice", "Normal"),
    FLYING7("Flying", "Fighting", "Super-effective"),
    FLYING8("Flying", "Poison", "Normal"),
    FLYING9("Flying", "Ground", "Normal"),
    FLYING10("Flying", "Flying", "Normal"),
    FLYING11("Flying", "Psychic", "Normal"),
    FLYING12("Flying", "Bug", "Super-effective"),
    FLYING13("Flying", "Rock", "Not very effective"),
    FLYING14("Flying", "Ghost", "Normal"),
    FLYING15("Flying", "Dragon", "Normal"),
    FLYING16("Flying", "Dark", "Normal"),
    FLYING17("Flying", "Steel", "Not very effective"),
    FLYING18("Flying", "Fairy", "Normal"),

    PSYCHIC1("Psychic", "Normal", "Normal"),
    PSYCHIC2("Psychic", "Fire", "Normal"),
    PSYCHIC3("Psychic", "Water", "Normal"),
    PSYCHIC4("Psychic", "Electric", "Normal"),
    PSYCHIC5("Psychic", "Grass", "Normal"),
    PSYCHIC6("Psychic", "Ice", "Normal"),
    PSYCHIC7("Psychic", "Fighting", "Super-effective"),
    PSYCHIC8("Psychic", "Poison", "Super-effective"),
    PSYCHIC9("Psychic", "Ground", "Normal"),
    PSYCHIC10("Psychic", "Flying", "Normal"),
    PSYCHIC11("Psychic", "Psychic", "Not very effective"),
    PSYCHIC12("Psychic", "Bug", "Normal"),
    PSYCHIC13("Psychic", "Rock", "Normal"),
    PSYCHIC14("Psychic", "Ghost", "Normal"),
    PSYCHIC15("Psychic", "Dragon", "Normal"),
    PSYCHIC16("Psychic", "Dark", "No effect"),
    PSYCHIC17("Psychic", "Steel", "Not very effective"),
    PSYCHIC18("Psychic", "Fairy", "Normal"),

    BUG1("Bug", "Normal", "Normal"),
    BUG2("Bug", "Fire", "Not very effective"),
    BUG3("Bug", "Water", "Normal"),
    BUG4("Bug", "Electric", "Normal"),
    BUG5("Bug", "Grass", "Super-effective"),
    BUG6("Bug", "Ice", "Normal"),
    BUG7("Bug", "Fighting", "Not very effective"),
    BUG8("Bug", "Poison", "Not very effective"),
    BUG9("Bug", "Ground", "Normal"),
    BUG10("Bug", "Flying", "Not very effective"),
    BUG11("Bug", "Psychic", "Super-effective"),
    BUG12("Bug", "Bug", "Normal"),
    BUG13("Bug", "Rock", "Normal"),
    BUG14("Bug", "Ghost", "Not very effective"),
    BUG15("Bug", "Dragon", "Normal"),
    BUG16("Bug", "Dark", "Super-effective"),
    BUG17("Bug", "Steel", "Not very effective"),
    BUG18("Bug", "Fairy", "Not very effective"),

    ROCK1("Rock", "Normal", "Normal"),
    ROCK2("Rock", "Fire", "Super-effective"),
    ROCK3("Rock", "Water", "Normal"),
    ROCK4("Rock", "Electric", "Normal"),
    ROCK5("Rock", "Grass", "Normal"),
    ROCK6("Rock", "Ice", "Super-effective"),
    ROCK7("Rock", "Fighting", "Not very effective"),
    ROCK8("Rock", "Poison", "Normal"),
    ROCK9("Rock", "Ground", "Not very effective"),
    ROCK10("Rock", "Flying", "Super-effective"),
    ROCK11("Rock", "Psychic", "Normal"),
    ROCK12("Rock", "Bug", "Super-effective"),
    ROCK13("Rock", "Rock", "Normal"),
    ROCK14("Rock", "Ghost", "Normal"),
    ROCK15("Rock", "Dragon", "Normal"),
    ROCK16("Rock", "Dark", "Normal"),
    ROCK17("Rock", "Steel", "Not very effective"),
    ROCK18("Rock", "Fairy", "Normal"),

    GHOST1("Ghost", "Normal", "No effect"),
    GHOST2("Ghost", "Fire", "Normal"),
    GHOST3("Ghost", "Water", "Normal"),
    GHOST4("Ghost", "Electric", "Normal"),
    GHOST5("Ghost", "Grass", "Normal"),
    GHOST6("Ghost", "Ice", "Normal"),
    GHOST7("Ghost", "Fighting", "Normal"),
    GHOST8("Ghost", "Poison", "Normal"),
    GHOST9("Ghost", "Ground", "Normal"),
    GHOST10("Ghost", "Flying", "Normal"),
    GHOST11("Ghost", "Psychic", "Super-effective"),
    GHOST12("Ghost", "Bug", "Normal"),
    GHOST13("Ghost", "Rock", "Normal"),
    GHOST14("Ghost", "Ghost", "Super-effective"),
    GHOST15("Ghost", "Dragon", "Normal"),
    GHOST16("Ghost", "Dark", "Not very effective"),
    GHOST17("Ghost", "Steel", "Normal"),
    GHOST18("Ghost", "Fairy", "Normal"),

    DRAGON1("Dragon", "Normal", "Normal"),
    DRAGON2("Dragon", "Fire", "Normal"),
    DRAGON3("Dragon", "Water", "Normal"),
    DRAGON4("Dragon", "Electric", "Normal"),
    DRAGON5("Dragon", "Grass", "Normal"),
    DRAGON6("Dragon", "Ice", "Normal"),
    DRAGON7("Dragon", "Fighting", "Normal"),
    DRAGON8("Dragon", "Poison", "Normal"),
    DRAGON9("Dragon", "Ground", "Normal"),
    DRAGON10("Dragon", "Flying", "Normal"),
    DRAGON11("Dragon", "Psychic", "Normal"),
    DRAGON12("Dragon", "Bug", "Normal"),
    DRAGON13("Dragon", "Rock", "Normal"),
    DRAGON14("Dragon", "Ghost", "Normal"),
    DRAGON15("Dragon", "Dragon", "Super-effective"),
    DRAGON16("Dragon", "Dark", "Normal"),
    DRAGON17("Dragon", "Steel", "Not very effective"),
    DRAGON18("Dragon", "Fairy", "No effect"),

    DARK1("Dark", "Normal", "Normal"),
    DARK2("Dark", "Fire", "Normal"),
    DARK3("Dark", "Water", "Normal"),
    DARK4("Dark", "Electric", "Normal"),
    DARK5("Dark", "Grass", "Normal"),
    DARK6("Dark", "Ice", "Normal"),
    DARK7("Dark", "Fighting", "Not very effective"),
    DARK8("Dark", "Poison", "Normal"),
    DARK9("Dark", "Ground", "Normal"),
    DARK10("Dark", "Flying", "Normal"),
    DARK11("Dark", "Psychic", "Super-effective"),
    DARK12("Dark", "Bug", "Normal"),
    DARK13("Dark", "Rock", "Normal"),
    DARK14("Dark", "Ghost", "Super-effective"),
    DARK15("Dark", "Dragon", "Normal"),
    DARK16("Dark", "Dark", "Not very effective"),
    DARK17("Dark", "Steel", "Normal"),
    DARK18("Dark", "Fairy", "Not very effective"),

    STEEL1("Steel", "Normal", "Normal"),
    STEEL2("Steel", "Fire", "Not very effective"),
    STEEL3("Steel", "Water", "Not very effective"),
    STEEL4("Steel", "Electric", "Not very effective"),
    STEEL5("Steel", "Grass", "Normal"),
    STEEL6("Steel", "Ice", "Super-effective"),
    STEEL7("Steel", "Fighting", "Normal"),
    STEEL8("Steel", "Poison", "Normal"),
    STEEL9("Steel", "Ground", "Normal"),
    STEEL10("Steel", "Flying", "Normal"),
    STEEL11("Steel", "Psychic", "Normal"),
    STEEL12("Steel", "Bug", "Normal"),
    STEEL13("Steel", "Rock", "Super-effective"),
    STEEL14("Steel", "Ghost", "Normal"),
    STEEL15("Steel", "Dragon", "Normal"),
    STEEL16("Steel", "Dark", "Normal"),
    STEEL17("Steel", "Steel", "Not very effective"),
    STEEL18("Steel", "Fairy", "Super-effective"),

    FAIRY1("Fairy", "Normal", "Normal"),
    FAIRY2("Fairy", "Fire", "Not very effective"),
    FAIRY3("Fairy", "Water", "Normal"),
    FAIRY4("Fairy", "Electric", "Normal"),
    FAIRY5("Fairy", "Grass", "Normal"),
    FAIRY6("Fairy", "Ice", "Normal"),
    FAIRY7("Fairy", "Fighting", "Super-effective"),
    FAIRY8("Fairy", "Poison", "Not very effective"),
    FAIRY9("Fairy", "Ground", "Normal"),
    FAIRY10("Fairy", "Flying", "Normal"),
    FAIRY11("Fairy", "Psychic", "Normal"),
    FAIRY12("Fairy", "Bug", "Normal"),
    FAIRY13("Fairy", "Rock", "Normal"),
    FAIRY14("Fairy", "Ghost", "Normal"),
    FAIRY15("Fairy", "Dragon", "Super-effective"),
    FAIRY16("Fairy", "Dark", "Super-effective"),
    FAIRY17("Fairy", "Steel", "Not very effective"),
    FAIRY18("Fairy", "Fairy", "Normal");

    private String attacker;
    private String defender;
    private String damageEffectiveness;

    private Database(String attacker, String defender, String damageEffectiveness) {
        this.attacker = attacker;
        this.defender = defender;
        this.damageEffectiveness = damageEffectiveness;
    }

    public String getAttacker( ) {
        return attacker;
    }

    public String getDefender() {
        return defender;
    }

    public String getDamageEffectiveness() {
        return damageEffectiveness;
    }
    // Override equals method that determines if the effectiveness of the attack is the same
    public boolean checkEquals(Object o) {
        if (o == this) return true;
        if (!(o instanceof Database)) {
            return false;
        }
        Database dictionary = (Database) o;
        return Objects.equals(damageEffectiveness, dictionary.damageEffectiveness);
    }
    // Override the ToString method
    public String toString() {
        return  "A " + attacker + " type attack " + damageEffectiveness.toLowerCase() + " against a " + defender + " type Pokemon";
    }
}
